name: Publish

on:
  create:
    tags:
      - v*

jobs:
  build-for-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Update GreenTunnel Core
        working-directory: ./gui
        run: npm install green-tunnel --save

      - name: Fix GUI Naming
        working-directory: ./gui
        run: |
          powershell -Command "(gc package.json) -replace 'green-tunnel-gui', 'green-tunnel' | Out-File -encoding ASCII package.json"
          powershell -Command "(gc package-lock.json) -replace 'green-tunnel-gui', 'green-tunnel' | Out-File -encoding ASCII package-lock.json"

      - name: Generate new icons files
        working-directory: ./gui
        run: npm run generate-icons

      - name: Build for Windows
        working-directory: ./gui
        run: npm run package-win

      - name: Add Windows Installer
        working-directory: ./gui
        run: npm run windows-installer

      - name: Save to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: builds-windows
          path: ./gui/release-builds/green-tunnel/windows-installer/green-tunnel-installer.exe

  build-for-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Dependencies
        working-directory: ./gui
        run: |
          npm ci
          npm install -g electron-installer-debian

      - name: Update GreenTunnel Core
        working-directory: ./gui
        run: npm install green-tunnel --save

      - name: Fix GUI Naming
        working-directory: ./gui
        run: |
          sed -i 's/green-tunnel-gui/green-tunnel/g' package.json
          sed -i 's/green-tunnel-gui/green-tunnel/g' package-lock.json

      - name: Generate new icons files
        working-directory: ./gui
        run: npm run generate-icons

      - name: Build for Linux
        working-directory: ./gui
        run: npm run package-linux

      - name: Add Linux Installer
        working-directory: ./gui
        run: npm run linux-installer

      - name: Zip
        working-directory: ./gui/release-builds
        run: zip -r green-tunnel-debian.zip *.deb

      - name: Save to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: builds-linux
          path: ./gui/release-builds/green-tunnel-debian.zip
